[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_2 = "vrRUFgnWdKNNqG9xgXoArH4k3mn4ZnpVNCQXHjN36ov"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/adityaanand/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
